version: '3.4'

services:
  todolist.api:
    image: ${DOCKER_REGISTRY-}todolistapi
    build:
      context: .
      dockerfile: src\ToDoList.Api\Dockerfile
    
  todolist.service:
    image: ${DOCKER_REGISTRY-}todolist.service
    build:
      context: .
      dockerfile: src\ToDoService\Dockerfile
    