version: '3.4'

services:
  todolist.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5001:443"
      - "5000:80"
    volumes:
      - C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:/appdata/Microsoft/UserSecrets
      - C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:/appdata/ASP.NET/Https

  
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/mnesia

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Todolist24app"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql/data

volumes:
   rabbitmqdata:
   dbdata: